import "./globals.css";
import { M_PLUS_Rounded_1c } from "next/font/google";

const mPlusR_1c = M_PLUS_Rounded_1c({
  subsets: ["latin"],
  weight: ["300", "400", "500", "700"],
});

// const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={mPlusR_1c.className}>{children}</body>
    </html>
  );
}
