import { mPlusRFont } from "~/lib/font";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html className={`${mPlusRFont.variable} font-sans`}>
      <body>{children}</body>
    </html>
  );
}
